name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        bin/setup

    - name: Run library tests
      run: |
        bundle exec rake test
    
    - name: Run dummy app tests (minitest)
      run: |
        cd test/dummy
        bundle exec rake test
      
    - name: Run dummy app tests (rspec)
      run: |
        cd test/dummy
        bundle exec rspec
    
    - name: Run JavaScript tests
      run: |
        cd lib/clapton/javascripts
        npm run test
